name: Backend Quality Check

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        pip install flake8 black pytest
    - name: Lint with flake8
      run: cd backend && flake8 .
    - name: Format with black
      run: cd backend && black --check .
    - name: Run tests
      run: cd backend && pytest
